name: CI

on:
  pull_request:
  push:
    branches:
      - Adding-CI

jobs:
  test-container:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build -t photo-app:${{ github.sha }} .

      - name: Run app
        run: |
          docker run -d -p 3000:3000 photo-app:${{ github.sha }}

      - name: Start ngrok
        run: |
          docker run -d \
            --name ngrok \
            -e NGROK_AUTHTOKEN=${{ secrets.NGROK_TOKEN }} \
            ngrok/ngrok:latest http host.docker.internal:3000